### ISSUE TITLE
Valo hoiya jan :D

### ISSUE THREAD

**Issue by shawanroy** [mdn522/mdn522#3]
Valo hoiya jan, Valo hoite poisa lage na :D

**Comment by mdn522** [comment]
Can you please elaborate

> Valo hoiya jan, Valo hoite poisa lage na :D

**Comment by shawanroy** [comment]
> Can you please elaborate
> 
> > Valo hoiya jan, Valo hoite poisa lage na :D

nop! btw valo hoye jan
